### ISSUE TITLE
Credential mapping to individual entities

### ISSUE THREAD

**Issue by neiljthomson** [decentralized-identity/credential-trust-establishment#6]
I suspect I'm missing something in looking at the University Diploma example.

While it's not clear what is contained in a credential for the role of "university_accreditor," it would be my understanding that each organization that is each university_accreditor will need its own credential (issued by the "US dept of education") vs. a single credential for all university_accreditors.

**Comment by TelegramSam** [comment]
The identifier present there (`RuuJwd3JMffNwZ43DcJKN1:2:University_Accreditation_Issuer:1.4`) is the schema that grants the university authority to issue (according to this governance) and is subject itself to the issuance restrictions also described within the same example.

If this doesn't yet make sense, Mike's PR will make it more obvious, as well as further refinements and explanations.

**Comment by TelegramSam** [comment]
No further questions indicated, closed for now. Please reopen if needed.
